"""Fetch-time `bun install`, so build actions never need the network.

A build action must not reach the network. A repository rule may -- that is the
same escape hatch `http_archive` already uses, and it is what makes a hermetic
frontend build possible without either vendoring `node_modules` into git or
punching a hole in the sandbox.

What this buys, concretely: the build depends on a tree pinned by `bun.lock`
rather than on whatever happens to sit in a developer's `node_modules`, and a
clean checkout builds the same bytes as a warm one.

Deliberately not rules_js/rules_ts, for the same reason `repositories.bzl`
records for the toolchain itself: they are pnpm-lockfile-based, which would
contradict README.md#language-tooling (`bun`, never `npm`). Build-as-last-resort per
README.md#upstream-first, because there is nothing here to adopt.
"""

load(":repositories.bzl", "BUN_VERSION", "PLATFORMS")

_BUILD_CONTENT = """\
# Generated by //tools/bazel/bun:deps.bzl -- do not edit.
#
# A glob rather than a directory: a repository rule cannot declare a
# TreeArtifact, so the installed tree is exposed as individual files. That is
# many thousands of them; it is the cost of not vendoring the tree into git.
filegroup(
    name = "node_modules",
    srcs = glob(["node_modules/**"], allow_empty = False),
    visibility = ["//visibility:public"],
)
"""

def _host_key(rctx):
    """Maps the host onto a PLATFORMS key, so the pins live in one file."""
    os_name = rctx.os.name.lower()
    arch = rctx.os.arch.lower()

    if os_name.startswith("mac"):
        os_part = "darwin"
    elif os_name.startswith("linux"):
        os_part = "linux"
    else:
        fail("bun_deps: unsupported host OS %r" % rctx.os.name)

    if arch in ("aarch64", "arm64"):
        arch_part = "aarch64"
    elif arch in ("x86_64", "amd64"):
        arch_part = "x64"
    else:
        fail("bun_deps: unsupported host arch %r" % rctx.os.arch)

    return os_part + "_" + arch_part

def _bun_deps_impl(rctx):
    platform = PLATFORMS[_host_key(rctx)]
    rctx.download_and_extract(
        url = "https://github.com/oven-sh/bun/releases/download/bun-v{v}/{asset}.zip".format(
            v = BUN_VERSION,
            asset = platform.asset,
        ),
        sha256 = platform.sha256,
        stripPrefix = platform.asset,
    )

    # Copied, not symlinked: bun resolves the project root from the manifest's
    # real path, so a symlinked package.json would install into the source tree
    # instead of into this repository.
    rctx.file("package.json", rctx.read(rctx.attr.package_json), executable = False)
    rctx.file("bun.lock", rctx.read(rctx.attr.lockfile), executable = False)

    # The archive's stored mode bit has historically not survived http_archive
    # consistently, the same reason bun_smoke_check chmods defensively.
    rctx.execute(["chmod", "+x", "bun"])

    result = rctx.execute(
        ["./bun", "install", "--frozen-lockfile", "--no-progress"],
        timeout = 600,
    )
    if result.return_code != 0:
        fail("bun_deps(%s): bun install failed (exit %d)\nstdout:\n%s\nstderr:\n%s" % (
            rctx.name,
            result.return_code,
            result.stdout,
            result.stderr,
        ))

    rctx.file("BUILD.bazel", _BUILD_CONTENT, executable = False)

bun_deps = repository_rule(
    implementation = _bun_deps_impl,
    doc = "Installs one bun package's dependencies at fetch time, pinned by its lockfile.",
    attrs = {
        "lockfile": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "The app's bun.lock. This is the pin; --frozen-lockfile enforces it.",
        ),
        "package_json": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "The app's package.json.",
        ),
    },
)
