#!/bin/bash
# tools/mirror-lifeos-commit.sh — land the LifeOS mirror on a schedule.
#
# WHAT IT CHANGES, STATED PLAINLY: mirror-lifeos-user.sh and mirror-lifeos-memory.sh
# both end their headers with "Committing stays a human step." That was the right call
# for a tool you run by hand, and it is exactly what failed. Measured 2026-08-17: four
# mirrored USER files sat modified and ten KNOWLEDGE notes sat untracked since 2026-08-16,
# because the mirror only ever lands when somebody commits axon-personal for some other
# reason. A backup that never leaves the disk holding the original is not a backup.
#
# So this script is the deliberate exception to that sentence, and nothing else in the
# mirror story changes: the two refresh tools still only ever copy INTO the overlay, and
# this one only ever commits paths under the mirror root.
#
#   tools/mirror-lifeos-commit.sh              # refresh, commit if changed, push
#   tools/mirror-lifeos-commit.sh --dry-run    # report what it would commit, write nothing
#   tools/mirror-lifeos-commit.sh --no-push    # commit locally, leave the push to a human
#   tools/mirror-lifeos-commit.sh --install    # write + load the LaunchAgent
#   tools/mirror-lifeos-commit.sh --uninstall  # unload + remove it
#
# WHY A STANDALONE LaunchAgent: every other com.axon.* plist is generated by
# service-runner.sh from a capability's service.toml, and they are all long-running
# services under a watchdog. This is a periodic maintenance task whose tools live in
# tools/, not a capability, so faking a service.toml for it would declare a bounded domain
# that does not exist. A second, smaller install path is the honest cost.
#
# EGRESS: the push sends the principal's identity and memory mirror to GitHub unattended.
# axon-personal is private, which bounds it, and --no-push exists for anyone who would
# rather that stayed a human decision.
#
# bash 3.2-safe.
set -euo pipefail

TOOLS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$TOOLS_DIR/lib/paths.sh"   # AXON_ROOT, AXON_PERSONAL_ROOT

LABEL="com.axon.lifeos-mirror"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
MIRROR_ROOT="resources/backups/lifeos"
INTERVAL="${AXON_MIRROR_INTERVAL:-3600}"

DRY_RUN=0
PUSH=1
case "${1:-}" in
  --dry-run)   DRY_RUN=1 ;;
  --no-push)   PUSH=0 ;;
  --install)   MODE=install ;;
  --uninstall) MODE=uninstall ;;
  --help|-h)   sed -n '2,29p' "$0"; exit 0 ;;
  "")          ;;
  *)           echo "unknown argument: $1" >&2; exit 2 ;;
esac

log() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*"; }

install_agent() {
  mkdir -p "$(dirname "$PLIST")"
  cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$TOOLS_DIR/mirror-lifeos-commit.sh</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>StartInterval</key>
  <integer>$INTERVAL</integer>
  <key>RunAtLoad</key>
  <false/>
  <key>StandardOutPath</key>
  <string>/tmp/axon-lifeos-mirror.log</string>
  <key>StandardErrorPath</key>
  <string>/tmp/axon-lifeos-mirror.err</string>
</dict>
</plist>
PLIST_EOF
  launchctl unload "$PLIST" 2>/dev/null || true
  launchctl load "$PLIST"
  log "installed $LABEL, every ${INTERVAL}s -> /tmp/axon-lifeos-mirror.log"
  # RunAtLoad is false on purpose: installing a backup job should not also fire an
  # unattended commit+push in the same second, before anyone has read what it would do.
  log "not fired yet; run '$0 --dry-run' to see what the first run would commit"
}

uninstall_agent() {
  launchctl unload "$PLIST" 2>/dev/null || true
  rm -f "$PLIST"
  log "removed $LABEL"
}

case "${MODE:-run}" in
  install)   install_agent; exit 0 ;;
  uninstall) uninstall_agent; exit 0 ;;
esac

# ---- the scheduled run -------------------------------------------------------

cd "$AXON_PERSONAL_ROOT" || { log "overlay not found: $AXON_PERSONAL_ROOT"; exit 0; }

# Never fight another git process, and never commit into a half-finished operation.
if [ -f .git/index.lock ]; then log "index.lock present, another git is running; skipping"; exit 0; fi
if [ -d .git/rebase-merge ] || [ -d .git/rebase-apply ] || [ -f .git/MERGE_HEAD ]; then
  log "rebase/merge in progress; skipping"; exit 0
fi
BRANCH="$(git symbolic-ref --quiet --short HEAD || true)"
if [ -z "$BRANCH" ]; then log "detached HEAD; skipping"; exit 0; fi

# --dry-run must mean it: the refresh tools default to report-only, and --apply is what
# makes them write. Passing --apply here and calling the run a dry one would have left the
# overlay modified by a command whose own help says it writes nothing.
APPLY="--apply"
[ "$DRY_RUN" = "1" ] && APPLY=""
"$TOOLS_DIR/mirror-lifeos-user.sh"   $APPLY >/dev/null 2>&1 || log "USER mirror refresh failed"
"$TOOLS_DIR/mirror-lifeos-memory.sh" $APPLY >/dev/null 2>&1 || log "MEMORY mirror refresh failed"

CHANGED="$(git status --porcelain -- "$MIRROR_ROOT" | wc -l | tr -d ' ')"
if [ "$CHANGED" = "0" ]; then log "mirror clean, nothing to commit"; exit 0; fi

if [ "$DRY_RUN" = "1" ]; then
  log "would commit $CHANGED path(s) under $MIRROR_ROOT:"
  git status --porcelain -- "$MIRROR_ROOT"
  exit 0
fi

# Stage the mirror root ONLY. Anything else dirty in the overlay belongs to whoever
# was working there and is never swept into an unattended commit.
git add -A -- "$MIRROR_ROOT"
git commit -q -m "backups: scheduled LifeOS mirror refresh ($CHANGED path(s))" \
  -m "Written by tools/mirror-lifeos-commit.sh on the $LABEL schedule. Only paths under $MIRROR_ROOT are staged." \
  || { log "commit produced nothing"; exit 0; }
log "committed $CHANGED path(s) on $BRANCH"

if [ "$PUSH" = "1" ]; then
  if git rev-parse --abbrev-ref --symbolic-full-name "@{u}" >/dev/null 2>&1; then
    git push --quiet && log "pushed $BRANCH" || log "push failed; the commit is local and will go with the next one"
  else
    log "$BRANCH has no upstream; commit stays local"
  fi
fi
